### ISSUE TITLE
Failed to Connect!

### ISSUE THREAD

**Issue by McRiot** [Sanae6/SmoOnlineServer#12]
Hey guys,

Just want to start by saying wonderful work! I realize this is a new project and I don't want to be a pest. Ever since I watched the video with 8 Player SpeedRun in SMO I set forth on my quest to run this Mod. 

I'll start with, I'm not using Homebrew (don't have it on my Switch), I read in comments it works with Ryujinx Emulator?

SMO vers 1.0 on Firmware 14.1.2 (also tried 14.1.0) - If theirs no chance of this working please just tell me, thanks.

So far,
Running on Ryujinx
SMO Works
Mod Loads and asks for an IP
I tried giving it a local IP (for my other computer)
I tried giving it my Public IP
I forwarded the port 1027
I allowed it to run through my firewall
Tried running the server on my Linux machine after giving up on Windows hosting

so I'm stuck, just 'Failed to Connect' every time.

**Comment by Sanae6** [comment]
I'll start by ignoring fact that you haven't homebrewed your switch and are asking about the mod lol.
If you are exclusively asking about the client, [the Discord server](https://discord.gg/jYCueK2BqD) would be the right place to ask.
Assuming you are specifically asking about the server, do you mind putting in your `settings.json` excluding any discord tokens in it? If you have changed the address from `0.0.0.0`, that most likely will cause issues. Firewall issues may be a big thing, and asking in the Discord server is something I'd recommend as this isn't the place to be talking about it.

**Comment by McRiot** [comment]
I don't mean to ruffle feathers, been at this a few hours and everything feels close to working.

I honestly don't know if it's the client or the server. I tried 0.0.0.0 as well as my local IP and public IP. Thank you for the discord, I'll hunt around for a solution. The only thing I changed in the settings.json was the IP Address assuming it would listen on the address I gave it. I've dealt with the Firewall ( I'm a computer tech, know a few things about networking )

Just wasn't sure if their was anything else in the settings.json I needed to configure other then the IP address.

for windows I ran the Server.exe with the setting 0.0.0.0 and attempted to connect to myself with 127.0.0.1.

Just scratching my head. Anyway, I'm on the discord server now reading stuff. Feel free to DM me if you think you can help out further otherwise I'm sure I'll get it sorted eventually. I don't want to overstep here. Thanks

**Comment by McRiot** [comment]
Solved the connection issue. Pinned msg in the Discord showed a setting in Ryujinx I was unaware of to enable network play.
