### ISSUE TITLE
keeps having to rejooin server again and again

### ISSUE THREAD

**Issue by mightymariomanlol** [Sanae6/SmoOnlineServer#25]
heres the issue i think idk.  
[Ryujinx_1.1.199_2022-07-31_14-15-34.log](https://github.com/Sanae6/SmoOnlineServer/files/9230475/Ryujinx_1.1.199_2022-07-31_14-15-34.log)

what happened is i joined my server in ryujinx... but i kept rejoining again and again. please help or atleast..   try to update smoonline server thx or the mod in general

**Comment by piplup55** [comment]
you didn't link the logs files right

**Comment by dF-Ex** [comment]
how?

**Comment by dF-Ex** [comment]
can u atleast fix this problem ill even show a video

**Comment by piplup55** [comment]
you linked the file path on your pc, you didn't upload them

**Comment by Sanae6** [comment]
All you sent were the locations of the files on your computer. Please upload your videos to a file hosting website and share a public link to them.

**Comment by dF-Ex** [comment]
heres the video incase u wanna know everythign else
https://www.youtube.com/watch?v=hxxhBn8ieRQ

**Comment by Sanae6** [comment]
The video is private, mark it as unlisted. May as well mention that the actual place to get help is [the Discord server](https://discord.gg/jYCueK2BqD), and this is for issues with the server, not for diagnosing of the client on an emulator.

**Comment by dF-Ex** [comment]
i made it unlisted

**Comment by piplup55** [comment]
1. you are using a emulator so you should build the [dev branch](https://github.com/CraftyBoss/SuperMarioOdysseyOnline/tree/dev) of the mod
2. like sanae said you should of asked in the [discord](https://discord.gg/jYCueK2BqD)

**Comment by Sanae6** [comment]
Closing, assuming it has been resolved.
