### ISSUE TITLE
Feature Request: A way to "rcon" into the systemd service

### ISSUE THREAD

**Issue by Melechtna** [Sanae6/SmoOnlineServer#26]
Title says it all, there's no way to send commands to the systemd service locally or remotely.

**Comment by piplup55** [comment]
being looked into, for now you can use a discord bot for commands

**Comment by Melechtna** [comment]
I managed to get this half working this way

create the needed input file
`mkfifo input`

Needs a script to attach to the process
`#!/bin/sh
tail -f /home/user/SMOServer/input| /home/user/SMOServer/Server
`
Then replacing the sh as the executable in the service file and can then write to it using
echo "send cap 0 1 user" > ./input

most of these assuming you're already in the SMOServer directory. It's inelegant and lacks a proper way to pipe in and get output, but hopefully that'll help someone in the right direct.

**Comment by piplup55** [comment]
@Melechtna could you try https://github.com/Sanae6/SmoOnlineServer/pull/27 it should have the feature now
