### ISSUE TITLE
how do i build smo online

### ISSUE THREAD

**Issue by mightymariomanlol** [Sanae6/SmoOnlineServer#28]
just a simple question, how do i build smo online, do i need requirments or something, if u do know how please let me know thx

**Comment by Istador** [comment]
See the [readme](https://github.com/Sanae6/SmoOnlineServer/blob/e7a3347a37ceaf030e36ce37d68487d2b15b09ab/README.md#building-maclinux-setup).

**Comment by hindexfindex** [comment]
i though thtis only works for smoonelineServer, are us sure this work for smo Online as well?

**Comment by piplup55** [comment]
smo server is the server software for the client

**Comment by Istador** [comment]
Do you mean the mod for the game?

That's in another repository: https://github.com/CraftyBoss/SuperMarioOdysseyOnline

This repository is for the server.

**Comment by hindexfindex** [comment]
oh ok i guess ill go there
