### ISSUE TITLE
Add a systemd for linux

### ISSUE THREAD

**Issue by vaporvee** [Sanae6/SmoOnlineServer#3]
Idk it doesn't work for me so could you add a .service .socket systemd thing for me? Everytime i close my putty server window the Smo Server closes

**Comment by Sanae6** [comment]
There are other ways of keeping the process alive, like using tmux or screen to hold the terminal session. There is also a [Docker based solution that's been created recently](https://github.com/d-touw/SMO_Online_Docker), though I haven't had a chance to test it myself.

I am not confident in my ability to make a good systemd file. If you want to contribute a systemd unit file, I'd be happy to look over a PR for it if someone makes one, but writing one myself is a bit much when I'm not experienced in doing so.
