### ISSUE TITLE
Prompt for IP and Port not appearing

### ISSUE THREAD

**Issue by Xarber** [Sanae6/SmoOnlineServer#47]
I am opening Mario Odyssey different times (With the mod installed, server set up and everything) and it's not prompting me to input an IP to my server. I also tried removing the 1.4.0 update but it only passed to 1.3.0, also I deleted the saves from the data manager but still nothing.

**Comment by Istador** [comment]
1. That the game isn't prompting you with IP/Port inputs has nothing to do with the server (this repository), but is a [client-side](https://github.com/CraftyBoss/SuperMarioOdysseyOnline) issue.
2. Afaik there is no `1.4.0`. The highest version number of SMO by Nintendo is `1.3.0`. The official SMOO server has a maximum version `1.0.3` and the SMOO client has versions `1.0.0` or `dev`.
3. Trying to remove updates from your Switch (or are you using an emulator? you didn't specify) is a bad idea and can get your console banned by Nintendo. There is a special odyssey downgrader that achieves a downgrade to SMO `1.0.0` without messing with installations. See [here](https://smoo.it/#/play/switch).
4. If the prompt isn't popping up that's usually one of two issues: either the game is not at SMO version `1.0.0` or the mod was installed incorrectly.

**Comment by Xarber** [comment]
sorry i didnt notice i was in the wrong repo. I am using 1.4.0 (i swear this is my SMO version) on actual hardware with emuMMC (cant ban my switch and i can play online on the stock). Removing updates only gets the game at 1.3.0, i will try using the other guide. Thanks

**Comment by Istador** [comment]
Well, given that the highest version I get from Nintendo when asking for an update for the game is `1.3.0` I assume you have some pirated/hacked version of SMO installed.

Probably even the downgrader won't work with that, because as you describe it the base version of the modified game seems to be `1.3.0` and not `1.0.0` as usual. So when the downgrader dumps the base version of the game, it will only downgrade it to `1.3.0` for you.

**Comment by Xarber** [comment]
it worked with the downgrader you sent. I do have a pirated version but now it works as usual
