### ISSUE TITLE
how do i join a server with server.exe

### ISSUE THREAD

**Issue by dF-Ex** [Sanae6/SmoOnlineServer#8]
hello, i was wondering how im suppost to join a server or join a user or do splitscreen if i want, if i cant do splitscreen i understand, but i want to do this thing where i can join a player in a server, is rhat what i do because i cant seem to figure it out, and if someone does please answer me thx

**Comment by Sanae6** [comment]
Support is not provided in the GitHub issues, you can join the Discord for [help here](https://discord.gg/jYCueK2BqD).
